
from dash import Dash, dcc, html, Input, Output  # pip install dash (version 2.0.0 or higher)

spaces = html.Div([
    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),

    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),

    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),

    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),

    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),

    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),

    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),

    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),
    html.Hr(),
    ]
)